In [2]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_excel('Datos_paises_despivotados.xlsx')

df

,Unnamed: 0,Country Name,Country Code,year,Bank nonperforming loans to total gross loans (%),Broad money (% of GDP),Current account balance (% of GDP),Deposit interest rate (%),Domestic credit to private sector (% of GDP),Domestic credit to private sector by banks (% of GDP),...,"Inflation, consumer prices (annual %)",Lending interest rate (%),Net barter terms of trade index (2015 = 100),"Official exchange rate (LCU per US$, period average)",Real interest rate (%),Short-term debt (% of total external debt),"Total debt service (% of exports of goods, services and primary income)",Total reserves in months of imports,Trade (% of GDP),"Unemployment, total (% of total labor force) (national estimate)"
0,0,Afghanistan,AFG,1970,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,38.692262,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Afghanistan,AFG,1971,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,38.692262,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Afghanistan,AFG,1972,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,38.692262,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Afghanistan,AFG,1973,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,38.692262,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Afghanistan,AFG,1974,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,38.378709,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13922,13922,Zimbabwe,ZWE,2020,NaN,10.002460,2.121236,4.518333,3.642132,3.607706,...,557.201817,33.008333,107.1,51.329013,-80.610262,29.5755,18.680976,0.062756,40.178406,NaN
13923,13923,Zimbabwe,ZWE,2021,NaN,10.239997,0.843388,8.059167,4.759522,4.759505,...,98.546105,45.476667,96.6,88.552447,-30.318195,26.4874,9.228518,1.148220,44.114559,9.459
13924,13924,Zimbabwe,ZWE,2022,NaN,12.673110,0.748243,34.720000,5.826323,5.826294,...,104.705171,131.813333,94.0,374.954363,-38.093651,28.1510,6.084244,0.704319,55.067352,10.001
13925,13925,Zimbabwe,ZWE,2023,NaN,11.204613,0.373211,62.820833,6.477697,6.477673,...,NaN,170.293833,99.1,3509.172220,-68.877267,27.0548,19.516072,0.129141,40.291261,9.290
13926,13926,Zimbabwe,ZWE,2024,NaN,NaN,1.206567,NaN,NaN,NaN,...,NaN,NaN,NaN,3266.331912,NaN,27.5425,NaN,0.519375,41.486531,12.130

In [7]:
target = pd.read_excel('TARGET.xlsx')
target

,Country,Systemic Banking Crisis (starting date),Currency Crisis,Sovereign Debt Crisis (year),Sovereign Debt Restructuring (year),a
0,NaN,NaN,(year),NaN,NaN,NaN
1,Albania,1994,1997,1990,1992,UNK
2,Algeria,1990,"1988, 1994",NaN,NaN,UNK
3,Angola,NaN,"1991, 1996, 2015",1988,1992,UNK
4,Argentina,"1980, 1989, 1995, 2001","1975, 1981, 1987, 2002, 2013","1982, 2001, 2014","1993, 2005, 2016",UNK
...,...,...,...,...,...,...
212,2015,NaN,13,1,NaN,NaN
213,2016,NaN,4,NaN,NaN,NaN
214,2017,NaN,NaN,2,NaN,NaN
215,Total,151,236,75,41,11
216,1/ Twin crisis indicates banking crisis in yea...,NaN,NaN,NaN,NaN,NaN

In [12]:
target['Country'] = target['Country'].str.strip()

In [15]:
lista_paises = target['Country'][1:56].to_list()

In [18]:
df_codigo = pd.DataFrame({'country':lista_paises})
df_codigo

                   country
0                  Albania
1                  Algeria
2                   Angola
3                Argentina
4                  Armenia
5                Australia
6                  Austria
7               Azerbaijan
8               Bangladesh
9                 Barbados
10                 Belarus
11                 Belgium
12                  Belize
13                   Benin
14                  Bhutan
15                 Bolivia
16  Bosnia and Herzegovina
17                Botswana
18                  Brazil
19                  Brunei
20                Bulgaria
21            Burkina Faso
22                 Burundi
23                Cambodia
24                Cameroon
25                  Canada
26              Cape Verde
27    Central African Rep.
28                    Chad
29                   Chile
30             China, P.R.
31                Colombia
32                 Comoros
33     Congo, Dem. Rep. of
34          Congo, Rep. of
35              Costa Rica
36           Côte d’Ivoire
37                 Croatia
38          Czech Republic
39                  Cyprus
40                 Denmark
41                Djibouti
42                Dominica
43      Dominican Republic
44                 Ecuador
45                   Egypt
46             El Salvador
47       Equatorial Guinea
48                 Eritrea
49                 Estonia
50                Ethiopia
51                    Fiji
52                 Finland
53                  France
54                   Gabon

In [21]:
import pycountry

def get_iso3(name):
    try:
        return pycountry.countries.lookup(name).alpha_3
    except:
        return None

def get_iso_numeric(name):
    try:
        return int(pycountry.countries.lookup(name).numeric)
    except:
        return None

In [22]:
df_codigo["iso3"] = df_codigo["country"].apply(get_iso3)
df_codigo["iso_numeric"] = df_codigo["country"].apply(get_iso_numeric)

In [23]:
df_codigo

                   country  iso3  iso_numeric
0                  Albania   ALB          8.0
1                  Algeria   DZA         12.0
2                   Angola   AGO         24.0
3                Argentina   ARG         32.0
4                  Armenia   ARM         51.0
5                Australia   AUS         36.0
6                  Austria   AUT         40.0
7               Azerbaijan   AZE         31.0
8               Bangladesh   BGD         50.0
9                 Barbados   BRB         52.0
10                 Belarus   BLR        112.0
11                 Belgium   BEL         56.0
12                  Belize   BLZ         84.0
13                   Benin   BEN        204.0
14                  Bhutan   BTN         64.0
15                 Bolivia   BOL         68.0
16  Bosnia and Herzegovina   BIH         70.0
17                Botswana   BWA         72.0
18                  Brazil   BRA         76.0
19                  Brunei  None          NaN
20                Bulgaria   BGR        100.0
21            Burkina Faso   BFA        854.0
22                 Burundi   BDI        108.0
23                Cambodia   KHM        116.0
24                Cameroon   CMR        120.0
25                  Canada   CAN        124.0
26              Cape Verde  None          NaN
27    Central African Rep.  None          NaN
28                    Chad   TCD        148.0
29                   Chile   CHL        152.0
30             China, P.R.  None          NaN
31                Colombia   COL        170.0
32                 Comoros   COM        174.0
33     Congo, Dem. Rep. of  None          NaN
34          Congo, Rep. of  None          NaN
35              Costa Rica   CRI        188.0
36           Côte d’Ivoire  None          NaN
37                 Croatia   HRV        191.0
38          Czech Republic   CZE        203.0
39                  Cyprus   CYP        196.0
40                 Denmark   DNK        208.0
41                Djibouti   DJI        262.0
42                Dominica   DMA        212.0
43      Dominican Republic   DOM        214.0
44                 Ecuador   ECU        218.0
45                   Egypt   EGY        818.0
46             El Salvador   SLV        222.0
47       Equatorial Guinea   GNQ        226.0
48                 Eritrea   ERI        232.0
49                 Estonia   EST        233.0
50                Ethiopia   ETH        231.0
51                    Fiji   FJI        242.0
52                 Finland   FIN        246.0
53                  France   FRA        250.0
54                   Gabon   GAB        266.0

In [24]:
df_codigo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      55 non-null     object
 1   iso3         48 non-null     object
 2   iso_numeric  48 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.4+ KB